# Generated by Django 5.2.1 on 2025-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
